### ISSUE TITLE
Build production editor app and  Build production web app fail on task ngAnnotate:dist

### ISSUE THREAD

**Issue by paolantoni** [WorldBank-Transport/DRIVER#781]
DRIVER VERSION 2.0.2

> Error:
> TASK [driver.web : Build production editor app] ********************************************************************************************************************************************************************************************************************************
> fatal: [app]: FAILED! => {"changed": true, 
> 						  "cmd": ["/usr/bin/docker",
> 								  "run", "--rm",
> 								  "--name",
> 								  "driver-editor",
> 								  "--volume",
> 								  "/opt/schema_editor/app/scripts/config.js:/opt/schema_editor/app/scripts/config.js",
> 								  "--volume", "/opt/schema_editor/dist:/opt/schema_editor/dist",
> 								  "--log-driver",
> 								  "syslog",
> 								  "quay.io/azavea/driver-editor:2.0.2",
> 								  "build"],
> 
> ......
> 
> 
> 001b[4mRunning \"ngAnnotate:dist\" (ngAnnotate) task\u001b[24m", "Generating \".tmp/concat/scripts/scripts.js\" from: \".tmp/concat/scripts/scripts.js\"...\u001b[31mERROR\u001b[39m", "\u001b[31m>> \u001b[39merror: couldn't process source due to parse error", "\u001b[31m>> \u001b[39mUnexpected token (16:21)", "\u001b[33mWarning: Task \"ngAnnotate:dist\" failed.\u0007 Use --force to continue.\u001b[39m", "", "\u001b[31mAborted due to warnings.\u001b[39m", "", "", "Execution Time (2019-05-20 15:58:06 UTC-0)", "concurrent:dist       6.4s  ???????????????????????????????? 76%", "autoprefixer:server  336ms  ?? 4%", "autoprefixer:dist    135ms  ? 2%", "ngAnnotate:dist       1.4s  ??????? 17%", "Total 8.4s"]}
>
fixed changing file:
deployment/ansible/roles/driver.web/tasks/staging_or_production.yml 
adding --force after build on both tasks.

`---
- name: Pull editor Docker image
  command: /usr/bin/docker pull {{ docker_repository }}driver-editor:{{ docker_image_tag }}

- name: Build production editor app
  command: >
    /usr/bin/docker run
      --rm
      --name driver-editor
      --volume {{ editor_scripts_dir }}/config.js:{{ editor_scripts_dir }}/config.js
      --volume {{ editor_build_dir }}:{{ editor_build_dir }}
      --log-driver syslog
      {{ docker_repository }}driver-editor:{{ docker_image_tag }}
      build **--force**

- name: Create editor data container
  command: >
    /usr/bin/docker create
      --volume {{ editor_dir }}
      --name driver-editor
    {{ docker_repository }}driver-editor:{{ docker_image_tag }}

- name: Pull web Docker image
  command: /usr/bin/docker pull {{ docker_repository }}driver-web:{{ docker_image_tag }}

- name: Build production web app
  command: >
    /usr/bin/docker run
      --rm
      --name driver-web
      --volumes-from driver-editor
      --volume {{ editor_scripts_dir }}/config.js:{{ editor_scripts_dir }}/config.js
      --volume {{ web_scripts_dir }}/config.js:{{ web_scripts_dir }}/config.js
      --volume {{ web_dir }}/app/index.html:{{ web_dir }}/app/index.html
      --volume {{ web_build_dir }}:{{ web_build_dir }}
      --log-driver syslog
      {{ docker_repository }}driver-web:{{ docker_image_tag }}
      build **--force**

- name: Remove editor data container
  command: >
    /usr/bin/docker rm --volumes --force driver-editor
`

**Comment by paolantoni** [comment]
forcing the build cause this error:

 stack: 'Error\\n    at new JS_Parse_Error (/npm/node_modules/uglify-js/lib/parse.js:196:18)\\n    at js_error (/npm/node_modules/uglify-js/lib/parse.js:204:11)\\n    at croak (/npm/node_modules/uglify-js/lib/parse.js:680:9)\\n    at token_error (/npm/node_modules/uglify-js/lib/parse.js:688:9)\\n    at unexpected (/npm/node_modules/uglify-js/lib/parse.js:694:9)\\n    at expr_atom (/npm/node_modules/uglify-js/lib/parse.js:1189:13)\\n    at maybe_unary (/npm/node_modules/uglify-js/lib/parse.js:1363:19)\\n    at expr_ops (/npm/node_modules/uglify-js/lib/parse.js:1398:24)\\n    at maybe_conditional (/npm/node_modules/uglify-js/lib/parse.js:1403:20)\\n    at maybe_assign (/npm/node_modules/uglify-js/lib/parse.js:1427:20)' }", 
        "\u001b[31m>> \u001b[39mUglifying source .tmp/concat/scripts/scripts.js failed.",

**Comment by paolantoni** [comment]
this bug exists also in 2.0.4.
According to Gruntfile.js:
schema_editor/Gruntfile.js:          cwd: '.tmp/concat/scripts',
schema_editor/Gruntfile.js:          dest: '.tmp/concat/scripts'
web/Gruntfile.js:          cwd: '.tmp/concat/scripts',
web/Gruntfile.js:          dest: '.tmp/concat/scripts'

are you sure that you can write on that path and the path exists?

**Comment by tgilcrest** [comment]
You shouldn't need to force the build to work, but rather try to resolve the error without forcing it. If you force it, there's no guarantee the build will continue to work after that point because whatever it was forced past will probably cascade down the rest of the process anyway.

The original error looks to be a parsing error of `ngAnnotate:dist`. We're not seeing this error when we build DRIVER from scratch. 

A couple of questions:
* Do you have local modifications to the files that deviate from the main codebase? 
* What is the latest commit that you've based your local branch on?

**Comment by paolantoni** [comment]
I'm building only from tags codebase.
Same error happened in 2.0.2, 2.0.3 and 2.0.4.
I'm building from scratch only editing the production file according to the documentation.
However i never managed to get the javascripts prepared by the build. I allways had to copy from the development (on the vagrant envs).

**Comment by rafaellpontes** [comment]
Hi Federico Paolantoni. I'm having the same problem. Did you solve this problem?

**Comment by paolantoni** [comment]
No. There is no way to debug because error occurs during the build with
ansible but inside the container started on the server.
Project developers should investigate.

Il gio 8 ago 2019, 19:33 rafaellpontes <notifications@github.com> ha
scritto:

**Comment by rafaellpontes** [comment]
The log was saying that an error occurred in the file web-config-js.j2, line "enabled: {{ web_js_html5mode }} "
I removed the line and the error disappeared. Then I got an error on certbot to install the ssl certificate. There is no package for cerbot on ubuntu 14.04, so you will have to install it manually https://certbot.eff.org/lets-encrypt/ubuntuother-nginx.html.
and prevent the certbot installation file from running (deployment/ansible/roles/driver.letsencrypt/tasks/main.yml).

Now I'm trying to solve this problem reported by you https://github.com/WorldBank-Transport/DRIVER/issues/786

**Comment by paolantoni** [comment]
I deployed successfully (but still with error on GTM) the 2.0.5 version.
